# Run tests and checks on every push

name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Typescript
        run: npm run build --if-present

      - name: Check code formatting
        run: npm run format

      - name: Run unit tests
        run: npm run test
